// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function getElmById(node) {
  return document.getElementById(node);
}

exports.getElmById = getElmById;
/* No side effect */
