// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function getElementById(node) {
  return document.getElementById(node);
}

exports.getElementById = getElementById;
/* No side effect */
