// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var DOM$Reason = require("./DOM.bs.js");

function createShader(gl, sType, source) {
  if (sType) {
    console.log("fragment");
    return /* () */0;
  } else {
    console.log("vertex");
    return /* () */0;
  }
}

function init(gl) {
  console.log("ready");
  console.log("fragment");
  return /* () */0;
}

var canvasNode = "webgl-canvas";

function setupContext(canvas) {
  var match = canvas.getContext("webgl2");
  if (match == null) {
    console.log("webgl2 context could not be created");
    return /* () */0;
  } else {
    return init(match);
  }
}

var match = DOM$Reason.getElmById(canvasNode);

if (match == null) {
  console.log("webgl-canvas element not found");
} else {
  setupContext(match);
}

exports.createShader = createShader;
exports.init = init;
exports.canvasNode = canvasNode;
exports.setupContext = setupContext;
/* match Not a pure module */
